-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Nov 28, 2019 at 04:32 PM
-- Server version: 5.7.26
-- PHP Version: 7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE db_artwork;
USE db_artwork;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_artwork`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_information`
--

CREATE TABLE `tbl_information` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Painting` varchar(100) NOT NULL,
  `Image` varchar(95) NOT NULL,
  `Artist` varchar(45) NOT NULL,
  `Year` int(15) NOT NULL,
  `Genre` varchar(50) NOT NULL,
  `Nationality` varchar(30) NOT NULL,
  `Description` varchar(750) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_information`
--

INSERT INTO `tbl_information` (`ID`, `Painting`, `Image`, `Artist`, `Year`, `Genre`, `Nationality`, `Description`) VALUES
(1, 'The Starry Night', 'painting1', 'Vincent van Gogh', 1889, 'Post-Impressionisn', 'Dutch', 'The oil-on-canvas painting is dominated by a night sky roiling with chromatic blue swirls, a glowing yellow crescent moon, and stars rendered as radiating orbs. One or two cypress trees, often described as flame-like, tower over the foreground to the left, their dark branches curling and swaying to the movement of the sky that they partly obscure. Amid all this animation, a structured village sits in the distance on the lower right of the canvas. Straight controlled lines make up the small cottages and the slender steeple of a church, which rises as a beacon against rolling blue hills. The glowing yellow squares of the houses suggest the welcoming lights of peaceful homes, creating a calm corner amid the painting’s turbulence.'),
(2, 'The Creation of Adam', 'painting2', 'Michelangelo', 1511, 'Renaissance', 'Italian', 'Adam on the left.  God is shown inside a floating nebulous form made up of  drapery and other figures.  The form is supported on angels who fly without wings, but whose flight is made clear by the drapery which whips out from underneath them. God is depicted as an elderly, yet muscular, man with grey hair and a long beard which react to the forward movement of flight.  This is a far cry from imperial images of God that had otherwise been created in the West dating back to the time of late antiquity.  Rather than wearing royal garments and depicted as an all-powerful ruler, he wears only a light tunic which leaves much of his arms and legs exposed.'),
(3, 'Mona Lisa', 'painting3', 'Leonardo da Vinci', 1503, 'Renaissance', 'Italian', 'The painting presents a woman in half-body portrait, which has as a backdrop a distant landscape. Yet this simple description of a seemingly standard composition gives little sense of Leonardo’s achievement. The three-quarter view, in which the sitter’s position mostly turns toward the viewer, broke from the standard profile pose used in Italian art and quickly became the convention for all portraits, one used well into the 21st century. The subject’s softly sculptural face shows Leonardo’s skillful handling of sfumato (use of fine shading) and reveals his understanding of the musculature and the skull beneath the skin. '),
(4, 'The Persistence of Memory', 'painting4', 'Salvador Dali', 1931, 'Surrealism', 'Spanish', 'Hard objects become inexplicably limp in this bleak and infinite dreamscape, while metal attracts ants like rotting flesh. Mastering what he called “the usual paralyzing tricks of eye-fooling,” Dalí painted with “the most imperialist fury of precision,” he said, but only “to systematize confusion and thus to help discredit completely the world of reality.” It is the classic Surrealist ambition, yet some literal reality is included, too: the distant golden cliffs are the coast of Catalonia, Dalí’s home.'),
(5, 'Impression, Sunrise', 'painting5', 'Claude Monet', 1872, 'Impressionism', 'French', 'This famous painting, Impression, Sunrise, was created from a scene in the port of Le Havre. Monet depicts a mist, which provides a hazy background to the piece set in the French harbor. The orange and yellow hues contrast brilliantly with the dark vessels, where little, if any detail is immediately visible to the audience. It is a striking and candid work that shows the smaller boats in the foregrouna almost being propelled along by the movement of the water. This has, once again, been achieved by separate brushstrokes that also show various colors \"sparkling\" on the sea.'),
(6, 'The Death of Marat', 'painting6', 'Jacques-Louis David', 1793, 'Neoclassicism', 'French', 'Here we have the death of a secular martyr on our hands, a Swiss journalist and agitator by the name of Jean-Paul Marat. He was killed by a woman called Charlotte Corday – a fragment of her letter, to him, slightly bloodied, is held in the dying man\'s left hand. She too was a revolutionary – but the wrong sort. She belonged to the Girondists and he to the Jacobins, and so, in her opinion, he had betrayed the spirit of the great cause, and the knife went in – you see it laid out, rather neatly, on the ground beside the tub, painted, smearily reddened, with such loving care.'),
(7, 'The Birth of Venus', 'painting7', 'Sandro Botticelli', 1485, 'Renaissance', 'Italian', 'Known as the “Birth of Venus”, the composition actually shows the goddess of love and beauty arriving on land, on the island of Cyprus, born of the sea spray and blown there by the winds, Zephyr and, perhaps, Aura. The goddess is standing on a giant scallop shell, as pure and as perfect as a pearl. She is met by a young woman, who is sometimes identified as one of the Graces or as the Hora of spring, and who holds out a cloak covered in flowers. Even the roses, blown in by the wind are a reminder of spring. The subject of the painting, which celebrates Venus as symbol of love and beauty, was perhaps suggested by the poet Agnolo Poliziano.'),
(8, 'The Scream', 'painting8', 'Edvard Munch', 1893, 'Expressionism', 'Norwegian', 'For all its notoriety, The Scream is in fact a surprisingly simple work, in which the artist utilized a minimum of forms to achieve maximum expressiveness. It consists of three main areas: the bridge, which extends at a steep angle from the middle distance at the left to fill the foreground; a landscape of shoreline, lake or fjord, and hills; and the sky, which is activated with curving lines in tones of orange, yellow, red, and blue-green. Foreground and background blend into one another, and the lyrical lines of the hills ripple through the sky as well. The human figures are starkly separated from this landscape by the bridge.'),
(9, 'Sunday Afternoon on the Island of La Grande Jatte', 'painting9', 'Georges-Pierre Seurat', 1884, 'Pointillism', 'French', 'Though the subjects of A Sunday Afternoon on the Island of La Grande Jatte are rendered in an unrealistic and almost minimalist style, Seurat opted to place them in a range of positions (“of some we see the backs, some we see full-face, some in profile, some are seated at right angles, some are stretched out horizontally, some are standing up straight,” art critic Félix Fénéon remarked in 1886). This decision adds a sense of realism to the otherwise stylized depiction and helps draws the viewer into the receding scenery.'),
(10, 'Ecstasy of Saint Teresa', 'painting10', 'Gian Lorenzo Bernini', 1647, 'Baroque', 'Italian', 'Saint Teresa describes an intensely spiritual encounter in physical, even sexual terms. Why? We know that an important goal of Baroque art is to involve the viewer.   Teresa explained her vision in this way to help us understand her extraordinary experience.   After all, being visited by an angel and filled with the love of God is no common event.  How can we, caught up in the realities of life, hope to understand the intensity and passion of her vision if not put in terms of our own human experiences?'),
(11, 'Girl with a Pearl Earring', 'painting11', 'Johannes Vermeer', 1665, 'Dutch Golden Age', 'Dutch', 'Girl with a Pearl Earring represents a young woman in a dark shallow space, an intimate setting that draws the viewer’s attention exclusively on her. She wears a blue and gold turban, the titular pearl earring, and a gold jacket with a visible white collar beneath. Her enigmatic expression coupled with the mystery of her identity has led some to compare her to the equivocal subject in Leonardo da Vinci’s Mona Lisa. Unlike the Mona Lisa, however, Girl with a Pearl Earring is not a portrait but a tronie, a Dutch term for a character or type of person. A young woman might have sat for Vermeer, but the painting is not meant to portray her or any specific individual in the same way that Leonardo’s piece portrayed an existing person. '),
(12, 'Where Do We Come From? What Are We? Where Are We Going?', 'painting12', 'Paul Gauguin', 1897, 'Post-Impressionism', 'French', 'Where are we going? represents the artist’s painted manifesto created while he was living on the island of Tahiti. The French artist  transitioned from being a “Sunday painter” (someone who paints for his or her own enjoyment) to becoming a professional after his career as a stockbroker failed in the early 1880s. He visited the Pacific island Tahiti in French Polynesia staying from 1891 to 1893. He then returned to Polynesia in 1895, painted this massive canvas there in 1897, and eventually died in 1903, on Hiva Oa in the Marquesas islands.'),
(13, 'The Lady of Shalott', 'painting13', 'John William Waterhouse', 1888, 'Romanticism', 'Italian', 'The landscape setting is highly naturalistic; the painting was made during Waterhouse’s brief period of plein-air painting. The setting is not identified, although the Waterhouses frequently visited Somerset and Devon. The model is traditionally said to be the artist’s wife. Waterhouse’s sketchbook contains numerous pencil studies for this and the painting of the same title made six years later (1894, Leeds City Art Gallery). This second work shows the Lady at the moment she looks out of the window and the curse is fulfilled. Waterhouse also made sketches of the final scenes in which the boat bearing the Lady floats into Camelot.'),
(14, 'Guernica', 'painting14', 'Pablo Picassso', 1937, 'Cubism', 'Spanish', 'Guernica shows the tragedies of war and the suffering it inflicts upon individuals, particularly innocent civilians. This work has gained a monumental status, becoming a perpetual reminder of the tragedies of war, an anti-war symbol, and an embodiment of peace. On completion Guernica was displayed around the world in a brief tour, becoming famous and widely acclaimed. This tour helped bring the Spanish Civil War to the world\'s attention.'),
(15, 'The Great Wave off Kanagawa', 'painting15', 'Hokusai', 1829, 'Ukiyo-e', 'Japanese', 'Hokusai has arranged the composition to frame Mount Fuji. The curves of the wave and hull of one boat dip down just low enough to allow the base of Mount Fuji to be visible, and the white top of the great wave creates a diagonal line that leads the viewers eye directly to the peak of the mountain top. Across the thirty-six prints that constitute this series, Hokusai varies his representation of the mountain. In other prints the mountain fills the composition, or is reduced to a small detail in the background of bustling city life.'),
(16, 'Liberty Leading the People', 'painting16', 'Eugène Delacroix', 1830, 'Romanticism', 'French', 'A half-nude female figure dominates the painting as she charges forward, a crowd of determined revolutionists in her wake. She is not a specific individual Delacroix saw fighting in the streets but rather a personification of the idea of liberty. She turns her head to check on her brigade, showing a profile that recalls those of rulers on Roman coins with her straight nose and full lips. She wears a red Phrygian cap, a hat resembling the stocking cap worn by contemporary French workingmen and made popular during the French Revolution (1787–99) as a “liberty cap” but which originates from antiquity.'),
(17, 'A Bar at the Folies-Bergère', 'painting17', 'Edouard Manet', 1882, 'Impressionism', 'French', 'This painting was Manet’s last major work. It represents the bustling interior of one of the most prominent music halls and cabarets of Paris, the Folies-Bergère. The venue opened in 1869 and its atmosphere was described as “unmixed joy”. In contrast, the barmaid in Manet’s representation is detached and marooned behind the bar. The Folies-Bergère was also notorious as a place to pick up prostitutes. The writer Guy de Maupassant described the barmaids as “vendors of drink and of love”.'),
(18, 'The Third of May 1808', 'painting18', 'Francisco Goya', 1814, 'Romanticism', 'Spanish', 'On May 2, 1808, hundreds of Spaniards rebelled. On May 3, these Spanish freedom fighters were rounded up and massacred by the French. Their blood literally ran through the streets of Madrid. Even though Goya had shown French sympathies in the past, the slaughter of his countrymen and the horrors of war made a profound impression on the artist. He commemorated both days of this gruesome uprising in paintings. Although Goya’s Second of May (above) is a tour de force of twisting bodies and charging horses reminiscent of Leonardo’s Battle of Anghiari, his The Third of May, 1808 in Madrid is acclaimed as one of the great paintings of all time, and has even been called the world’s first modern painting.'),
(19, 'American Gothic', 'painting19', 'Grant Wood', 1930, 'Modernism', 'American', 'Grant Wood’s American Gothic caused a stir in 1930 when it was exhibited for the first time at the Art Institute of Chicago and awarded a prize of 300 dollars. Newspapers across the country carried the story, and the painting of a farm couple posed before a white house brought the artist instant fame. The Iowa native, then in his late 30s, was enchanted by a cottage he had seen in the small southern Iowa town of Eldon. Its Gothic Revival style, indicated by the upper window designed to resemble a medieval pointed arch, inspired the painting’s title.'),
(20, 'The Thinker', 'painting20', 'Auguste Rodin', 1902, 'Realism', 'French', 'The Thinker was originally conceived not in heroic isolation, but as part of Rodin\'s monumental Gates of Hell—a pair of bronze doors intended for a museum of decorative arts in Paris. Although the doors were never cast during the sculptor\'s lifetime, they nevertheless provided Rodin a rich source of ideas for individual figures and groups that he worked and reworked for the rest of his career.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
